dist: focal
before_install:
 - sudo apt-get update
install: 
 - gem install kramdown-rfc2629
 - sudo pip install xml2rfc
 - sudo apt-get install npm
 - sudo npm install cspell@cspell4 -g
script: make full
